//app.js
App({
  onLaunch: function () {

  },
  globalData: {
    RoleList:[
      {
        RoleId:1001,
        RoleName:'平民',
        RoleType:0,         //身份类型(0=>民 1=>狼  2=>神)
        Photo:'../../resources/images/role/children.png',
        Num:4,
      },
      {
        RoleId:1002,
        RoleName:'狼人',
        RoleType:1,         //身份类型(0=>民 1=>狼  2=>神)
        Photo:'../../resources/images/role/woof.png',
        Num:4,
      },
      {
        RoleId:1003,
        RoleName:'预言家',
        RoleType:2,
        Photo:'../../resources/images/role/god.png',
        Num:1,
      },
      {
        RoleId:1004,
        RoleName:'女巫',
        RoleType:2,
        Photo:'../../resources/images/role/witch.png',
        Num:1,
      },
      {
        RoleId:1005,
        RoleName:'守卫',
        RoleType:2,
        Photo:'../../resources/images/role/god.png',
        Num:1,
      },
      {
        RoleId:1006,
        RoleName:'猎人',
        RoleType:2,
        Photo:'../../resources/images/role/children.png',
        Num:1,
      },
    ],
    CurrentList: [   //玩家列表（配置好人数后点开始游戏,打乱身份 并存入该列表）
                     //后续拍照啥的都存到这个列表 
      {
        Id:1,
        RoleName:'狼人',
        RoleType:1,
        playerPic:'照片地址',
      },
      {
        Id:2,
        RoleName:'平民',
        RoleType:0,
        playerPic:'照片地址',
      },
      {
        Id:3,
        RoleName:'平民',
        RoleType:0,
        playerPic:'照片地址',
      }
    ]
  }
})